controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

#hasard:
    #path: /home
    #controller: App\Controller\General::chance